name: CI/CD Pipeline

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create application.yml
        run: |
          cd ./src/main/resources
          printf "%s" "${{ secrets.APPLICATION_YML }}" > application.yml

      - name: Debug application.yml
        run: cat ./src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          cache-disabled: false

      - name: Run tests
        run: ./gradlew test -Dspring.profiles.active=test
